# Generated by Django 2.2.24 on 2023-04-24 08:52
from django.db import migrations


def fill_flat_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = True
        if not flat.construction_year or flat.construction_year < 2015:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_flat_new_building)
    ]
