# Generated by Django 2.2.24 on 2023-04-24 10:33
import phonenumbers
from django.db import migrations


def fill_flat_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = None
        if phonenumbers.is_valid_number(phone_number):
            cleared_phone_number = phonenumbers.format_number(
                phone_number,
                phonenumbers.PhoneNumberFormat.INTERNATIONAL
            )
            flat.owner_pure_phone = cleared_phone_number
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_flat_owner_pure_phone)
    ]
