# Generated by Django 2.2.24 on 2023-04-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230424_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='like_by',
            new_name='liked_by',
        ),
    ]
